### ISSUE TITLE
Compilation failed with nginx 1.13.6

### ISSUE THREAD

**Issue by sidv93** [SpiderLabs/ModSecurity#2269]
**Expected behavior**

Modsecurity expected to compile on Ubuntu 18.04 with nginx 1.13.6 and latest Modsecurity v3 nginx connector

**Server (please complete the following information):**
 - ModSecurity version (and connector):  ModSecurity v3.0.4 with nginx-connector v1.0.1
 - WebServer: nginx-1.13.6
 - OS (and distro): Ubuntu 18.04

**Steps to reproduce:**
 - Clone v3/master branch
 - git submodule init
 - git submodule update
 - ./build.sh
 - ./configure
 - make
 - make install
 - "./configure --with-compat --add-dynamic-module=/path/to/ModSecurity-nginx" from nginx folder
 - make modules

**Error logs:**

```
make modules
make -f objs/Makefile modules
make[1]: Entering directory '/home/nginx-1.13.6'
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/modsecurity/include -I objs -I src/http -I src/http/modules \
	-o objs/addon/src/ngx_http_modsecurity_module.o \
	/home/ModSecurity/ModSecurity-nginx/src/ngx_http_modsecurity_module.c
In file included from /home/ModSecurity/ModSecurity-nginx/src/ngx_http_modsecurity_module.c:21:0:
/home/ModSecurity/ModSecurity-nginx/src/ngx_http_modsecurity_common.h:40:31: fatal error: modsecurity/rules.h: No such file or directory
 #include <modsecurity/rules.h>
                               ^
compilation terminated.
objs/Makefile:1214: recipe for target 'objs/addon/src/ngx_http_modsecurity_module.o' failed
make[1]: *** [objs/addon/src/ngx_http_modsecurity_module.o] Error 1
make[1]: Leaving directory '/home/nginx-1.13.6'
Makefile:14: recipe for target 'modules' failed
make: *** [modules] Error 2
```

**Comment by zimmerle** [comment]
wip

**Comment by zimmerle** [comment]
Fixed by 4e9ba44d034c7afdf23bacea948b3b9961f424dc
