### ISSUE TITLE
Does it work with Nginx 1.23.x version ?

### ISSUE THREAD

**Issue by Tarun1286** [SpiderLabs/ModSecurity#2882]
Not able to compile modsecurity version 2.9.4 with Nginx 1.23.x. Does the new version 2.9.7 support Nginx 1.23.x?

**Logs and dumps**

Output of:
 [2023-03-14T05:08:43.714Z] /modsecurity-2.9.4/nginx/modsecurity/ngx_http_modsecurity.c
[2023-03-14T05:08:43.714Z] /modsecurity-2.9.4/nginx/modsecurity/ngx_http_modsecurity.c: In function ‘ngx_http_modsecurity_save_headers_in’:
[2023-03-14T05:08:43.714Z] modsecurity-2.9.4/nginx/modsecurity/ngx_http_modsecurity.c:382:39: error: ‘ngx_http_headers_in_t’ {aka ‘struct <anonymous>’} has no member named ‘cookies’; did you mean ‘cookie’?
[2023-03-14T05:08:43.714Z]      if (ngx_array_init(&r->headers_in.cookies, r->pool, 2,
[2023-03-14T05:08:43.714Z]                                        ^~~~~~~
[2023-03-14T05:08:43.714Z]                                        cookie

**Comment by martinhsv** [comment]
Hello @Tarun1286 ,

For use with nginx, you should be using ModSecurity v3.0.x.
