### ISSUE TITLE
Ubuntu 18.04 with Nginx 1.17.8 - build fails when compiling from source using ModSecurity - v3.0.4-24-gb7e28c24 for Linux

### ISSUE THREAD

**Issue by argupta23** [SpiderLabs/ModSecurity#2264]
Build Failing while installing on Ubuntu 18.04  and Nginx 1.17.8 with below error:

`
ModSecurity - v3.0.4-24-gb7e28c24 for Linux

 Mandatory dependencies
   + libInjection                                  ....v3.0.4-24-gb7e28c24
   + SecLang tests                                 ....b7e28c24

 Optional dependencies
   + GeoIP/MaxMind                                 ....found
      * (GeoIP) v1.6.12
         -lGeoIP  , -I/usr/include/
   + LibCURL                                       ....found v7.58.0
      -lcurl,  -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
   + YAJL                                          ....found v2.1.0
      -lyajl  , -DWITH_YAJL -I/usr/include/yajl
   + LMDB                                          ....disabled
   + LibXML2                                       ....found v2.9.4
      -lxml2, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....not found
   + LUA                                           ....not found

 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled

**### vagrant@digest:~/nginx-1.17.8/ModSecurity$ make**

Making all in others
make[1]: Entering directory '/home/vagrant/nginx-1.17.8/ModSecurity/others'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/vagrant/nginx-1.17.8/ModSecurity/others'
Making all in src
make[1]: Entering directory '/home/vagrant/nginx-1.17.8/ModSecurity/src'
make  all-recursive
make[2]: Entering directory '/home/vagrant/nginx-1.17.8/ModSecurity/src'
make[3]: Entering directory '/home/vagrant/nginx-1.17.8/ModSecurity/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/      -DWITH_YAJL -I/usr/include/yajl    -DPCRE_HAVE_JIT    -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT parser/libmodsecurity_la-seclang-parser.lo -MD -MP -MF parser/.deps/libmodsecurity_la-seclang-parser.Tpo -c -o parser/libmodsecurity_la-seclang-parser.lo `test -f 'parser/seclang-parser.cc' || echo './'`parser/seclang-parser.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/ -DWITH_YAJL -I/usr/include/yajl -DPCRE_HAVE_JIT -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT parser/libmodsecurity_la-seclang-parser.lo -MD -MP -MF parser/.deps/libmodsecurity_la-seclang-parser.Tpo -c parser/seclang-parser.cc  -fPIC -DPIC -o parser/.libs/libmodsecurity_la-seclang-parser.o
In file included from ../src/rule_script.h:21:0,
                 from seclang-parser.yy:20,
                 from parser/seclang-parser.cc:40:
../headers/modsecurity/rules_set.h: In constructor ‘modsecurity::RulesSet::RulesSet()’:
../headers/modsecurity/rules_set.h:51:9: error: expected identifier before ‘,’ token
         ,m_secmarker_skipped(0)
         ^
Makefile:1851: recipe for target 'parser/libmodsecurity_la-seclang-parser.lo' failed
make[3]: *** [parser/libmodsecurity_la-seclang-parser.lo] Error 1
make[3]: Leaving directory '/home/vagrant/nginx-1.17.8/ModSecurity/src'
Makefile:3223: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/vagrant/nginx-1.17.8/ModSecurity/src'
Makefile:1016: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/vagrant/nginx-1.17.8/ModSecurity/src'
Makefile:1026: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`
To Reproduce

**Steps to reproduce the behaviour:**
git clone https://github.com/SpiderLabs/ModSecurity.git
cd ModSecurity/
sudo apt install apt-utils autoconf automake build-essential git libcurl4-openssl-dev libgeoip-dev liblmdb-dev libpcre++-dev libtool libxml2-dev libyajl-dev pkgconf wget zlib1g-dev
./build.sh
git submodule init
git submodule update
./configure
make

**Comment by argupta23** [comment]
It looks like it is an issue with the ModSecurity ModSecurity - v3.0.4-24-gb7e28c24 for Linux.

I know that this actually works with Nginx 1.17.6 and ModSecurity - v3.0.4-18-gf7e4c1d9 for Linux

ModSecurity - v3.0.4-18-gf7e4c1d9 for Linux

 Mandatory dependencies
   + libInjection                                  ....v3.0.4-18-gf7e4c1d9
   + SecLang tests                                 ....f7e4c1d9

 Optional dependencies
   + GeoIP/MaxMind                                 ....found
      * (GeoIP) v1.6.12
         -lGeoIP  , -I/usr/include/
   + LibCURL                                       ....found v7.58.0
      -lcurl,  -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
   + YAJL                                          ....found v2.1.0
      -lyajl  , -DWITH_YAJL -I/usr/include/yajl
   + LMDB                                          ....disabled
   + LibXML2                                       ....found v2.9.4
      -lxml2, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....not found
   + LUA                                           ....not found

 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled

**Comment by airween** [comment]
May be you should go back to [f7e4c1](https://github.com/SpiderLabs/ModSecurity/commit/f7e4c1d9f5c96429334a28561fd2dd8cc4b53d30)

```
git checkout f7e4c1
```

**Comment by argupta23** [comment]
> May be you should go back to [f7e4c1](https://github.com/SpiderLabs/ModSecurity/commit/f7e4c1d9f5c96429334a28561fd2dd8cc4b53d30)
> 
> ```
> git checkout f7e4c1
> ```

yes that is what I did.

**Comment by Viktova** [comment]
https://github.com/SpiderLabs/ModSecurity/issues/2266
