### ISSUE TITLE
Fails to compile on ubuntu:xenial (16.04)

### ISSUE THREAD

**Issue by stevenmunro** [SpiderLabs/ModSecurity#1182]
Hello
I'm following the 15.04 compilation recipe at https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes#ubuntu-1504

I added liblmdb-dev to the apt-get line.

At the end of make I get this error

`Making all in doc
make[1]: Entering directory '/opt/ModSecurity/doc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/opt/ModSecurity/doc'
Making all in examples
make[1]: Entering directory '/opt/ModSecurity/examples'
Making all in simple_example_using_c
make[2]: Entering directory '/opt/ModSecurity/examples/simple_example_using_c'
gcc -DHAVE_CONFIG_H -I. -I../../src    -I../../headers -I../..  -g -O2 -MT test-test.o -MD -MP -MF .deps/test-test.Tpo -c -o test-test.o `test -f 'test.c' || echo './'`test.c
mv -f .deps/test-test.Tpo .deps/test-test.Po
/bin/bash ../../libtool  --tag=CC   --mode=link gcc -I../../headers -I../..  -g -O2   -o test test-test.o -L../../src/.libs/ -lmodsecurity  -L/usr/lib/x86_64-linux-gnu/ -lrt
libtool: link: gcc -I../../headers -I../.. -g -O2 -o .libs/test test-test.o  -L../../src/.libs/ /opt/ModSecurity/src/.libs/libmodsecurity.so -L/usr/lib/x86_64-linux-gnu/ -lrt -pthread -Wl,-rpath -Wl,/usr/local/modsecurity/lib
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_create'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_begin'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_get'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `yajl_complete_parse'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_put'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_get'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_abort'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_commit'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `yajl_config'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `yajl_parse'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `yajl_get_error'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `yajl_alloc'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_dbi_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_dbi_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_del'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `yajl_free'
collect2: error: ld returned 1 exit status
Makefile:454: recipe for target 'test' failed
make[2]: *** [test] Error 1
make[2]: Leaving directory '/opt/ModSecurity/examples/simple_example_using_c'
Makefile:456: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/ModSecurity/examples'
Makefile:894: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1`

I have no idea where to start looking. Any help appreciated.

**Comment by csanders-git** [comment]
looks like your yajl headers aren't properly linked. Maybe an old version?

**Comment by stevenmunro** [comment]
Ok, this is a clean install of xenial. 
./configure reveals that under 'Optional Dependencies' that -    + YAJL     ....not found

**Comment by stevenmunro** [comment]
apt-get install libyajl-dev
libyajl-dev is already the newest version (2.1.0-2).

**Comment by stevenmunro** [comment]
apt-get install libyajl2
libyajl2 is already the newest version (2.1.0-2).

**Comment by csanders-git** [comment]
yeah @zimmerle YAJL is no longer optional right?

In any event certain distro's don't place the pkgconfig-file for YAJL because they like to watch the world burn. Can you search your system for 'yajl.pc'?

**Comment by stevenmunro** [comment]
find /usr -name "yajl.pc"
/usr/lib/x86_64-linux-gnu/pkgconfig/yajl.pc

**Comment by stevenmunro** [comment]
Not sure if related but..
./configure: line 5172: PKG_PROG_PKG_CONFIG: command not found

**Comment by stevenmunro** [comment]
Solved YAJL issue with
$ apt-get install pkgconf
$ autoreconf -i
$ automake
$ autoconf
$ ./configure

+ YAJL                                          ....found v2.1.0

however, make still reports same original error as above.

**Comment by csanders-git** [comment]
with the yajl_* errors?

**Comment by stevenmunro** [comment]
Yeah still there. I'll paste the latest output here.

Making all in src
make[1]: Entering directory '/opt/ModSecurity/src'
make  all-am
make[2]: Entering directory '/opt/ModSecurity/src'
make[2]: Leaving directory '/opt/ModSecurity/src'
make[1]: Leaving directory '/opt/ModSecurity/src'
Making all in doc
make[1]: Entering directory '/opt/ModSecurity/doc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/opt/ModSecurity/doc'
Making all in examples
make[1]: Entering directory '/opt/ModSecurity/examples'
Making all in simple_example_using_c
make[2]: Entering directory '/opt/ModSecurity/examples/simple_example_using_c'
/bin/bash ../../libtool  --tag=CC   --mode=link gcc -I../../headers -I../..  -g -O2   -o test test-test.o -L../../src/.libs/ -lmodsecurity   -lrt
libtool: link: gcc -I../../headers -I../.. -g -O2 -o .libs/test test-test.o  -L../../src/.libs/ /opt/ModSecurity/src/.libs/libmodsecurity.so -lrt -pthread -Wl,-rpath -Wl,/usr/local/modsecurity/lib
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_create'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_begin'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_get'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `yajl_complete_parse'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_put'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_get'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_abort'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_commit'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `yajl_config'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `yajl_parse'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `yajl_get_error'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `yajl_alloc'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_dbi_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_dbi_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_del'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `yajl_free'
collect2: error: ld returned 1 exit status
Makefile:457: recipe for target 'test' failed
make[2]: *** [test] Error 1
make[2]: Leaving directory '/opt/ModSecurity/examples/simple_example_using_c'
Makefile:459: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/ModSecurity/examples'
Makefile:897: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by stevenmunro** [comment]
Ok, I started from fresh (new ubuntu:xenial)
The YAJL issue is gone, but it does appear to be complaining about MDB..

/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_create'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_begin'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_get'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_put'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_get'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_abort'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_commit'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_dbi_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_dbi_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_del'

**Comment by stevenmunro** [comment]
This may be why

./configure: line 5809: PROG_LMDB: command not found

**Comment by zimmerle** [comment]
Hi @stevenmunro,

There are two missing dependencies:

- libYAJL - Used by everything that uses JSON: Parser, Log generation and so on..
- lmdb - Used for persistent storage / Global collections.

Looking at the error message, it seems like the headers were found (for both libraries) but the library elf (the .so file) were not found - at least not the "right"  one. There are various possibilities that may lead to that, including the possibility two different versions of the libraries being installed on the same machine. Do you mind to share your config.log via gists? So we can have a better picture of the configuration variables.

**Comment by manishmalik** [comment]
I am also having the similar issue (lmdb undefined reference):
```
ubuntu:/opt/ModSecurity$ sudo make
Making all in others
make[1]: Entering directory `/opt/ModSecurity/others'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/opt/ModSecurity/others'
Making all in src
make[1]: Entering directory `/opt/ModSecurity/src'
make  all-am
make[2]: Entering directory `/opt/ModSecurity/src'
make[2]: Leaving directory `/opt/ModSecurity/src'
make[1]: Leaving directory `/opt/ModSecurity/src'
Making all in doc
make[1]: Entering directory `/opt/ModSecurity/doc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/opt/ModSecurity/doc'
Making all in examples
make[1]: Entering directory `/opt/ModSecurity/examples'
Making all in simple_example_using_c
make[2]: Entering directory `/opt/ModSecurity/examples/simple_example_using_c'
/bin/bash ../../libtool  --tag=CC   --mode=link gcc -I../../headers -I../..  -g -O2   -o test test-test.o -L../../src/.libs/ -lmodsecurity   -lrt   
libtool: link: gcc -I../../headers -I../.. -g -O2 -o .libs/test test-test.o  -L../../src/.libs/ /opt/ModSecurity/src/.libs/libmodsecurity.so -lrt -pthread
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_create'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_commit'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_begin'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_del'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_get'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_dbi_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_dbi_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_put'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_get'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_abort'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_open'
collect2: error: ld returned 1 exit status
make[2]: *** [test] Error 1
make[2]: Leaving directory `/opt/ModSecurity/examples/simple_example_using_c'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/ModSecurity/examples'
make: *** [all-recursive] Error 1
```
[config.log](https://gist.github.com/manishmalik/a42bef677929b4e172001c18a8af11dc)

`liblmdb.so` is available at `/usr/lib/x86_64-linux-gnu` in my system. Let me know if you need more info.

**Comment by zimmerle** [comment]
Can you check if you have a file named:

```
/usr/include/lmdb.h
```

What is yours lmdb version?

**Comment by manishmalik** [comment]
Yes, `lmdb.h` is available at `/usr/include/`.

Mine lmdb version is 0.9.10-1.

Also, seems like its fixed from this commit : https://github.com/SpiderLabs/ModSecurity/commit/4c8aa54099643b79074fc68576e1fbae09dd7355

@stevenmunro you may also confirm the same.

**Comment by zimmerle** [comment]
I am closing the issue based on @manishmalik comment. Thanks!

**Comment by tahirramzan** [comment]
Not working for me from this commit:  [(https://github.com/SpiderLabs/ModSecurity/commit/4c8aa54099643b79074fc68576e1fbae09dd7355)]

` sudo make
Making all in others
make[1]: Entering directory '/opt/ModSecurity/others'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/opt/ModSecurity/others'
Making all in src
make[1]: Entering directory '/opt/ModSecurity/src'
make  all-am
make[2]: Entering directory '/opt/ModSecurity/src'
make[2]: Leaving directory '/opt/ModSecurity/src'
make[1]: Leaving directory '/opt/ModSecurity/src'
Making all in doc
make[1]: Entering directory '/opt/ModSecurity/doc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/opt/ModSecurity/doc'
Making all in examples
make[1]: Entering directory '/opt/ModSecurity/examples'
Making all in simple_example_using_c
make[2]: Entering directory '/opt/ModSecurity/examples/simple_example_using_c'
/bin/bash ../../libtool  --tag=CC   --mode=link gcc -I../../headers -I../..  -g -O2   -o test test-test.o -L../../src/.libs/ -lmodsecurity   -lrt   
libtool: link: gcc -I../../headers -I../.. -g -O2 -o .libs/test test-test.o  -L../../src/.libs/ /opt/ModSecurity/src/.libs/libmodsecurity.so -lrt -pthread -Wl,-rpath -Wl,/usr/local/modsecurity/lib
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_create'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_begin'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_get'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_put'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_get'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_abort'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_txn_commit'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_env_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_cursor_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_dbi_close'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_dbi_open'
/opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `mdb_del'
collect2: error: ld returned 1 exit status
Makefile:464: recipe for target 'test' failed
make[2]: *** [test] Error 1
make[2]: Leaving directory '/opt/ModSecurity/examples/simple_example_using_c'
Makefile:466: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/ModSecurity/examples'
Makefile:911: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

**Comment by tahirramzan** [comment]
If the problem is still occurring then clean your local git repository through:

git gc
git clean -d -x -f
